# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2017

# Branches to build
branches:
  only: 
    - master

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
    - type: Cygwin
      build: C:\cygwin64\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/sample/CppLogging/build; exec 0</dev/null; ./cygwin.sh"
      command: C:\cygwin64\bin\bash -lc
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Chocolatey
  - choco upgrade chocolatey
  # Cygwin
  - if "%type%"=="Cygwin" if not exist "C:\cygwin64" mkdir "C:\cygwin64"
  - if "%type%"=="Cygwin" appveyor-retry appveyor DownloadFile "http://cygwin.com/setup-x86_64.exe" -FileName "C:\cygwin64\setup-x86_64.exe"
  - if "%type%"=="Cygwin" C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --root "C:\cygwin64" --local-package-dir "C:\cache\cygwin" --packages cmake,automake,make,gcc-core,gcc-g++,librhash0,libuv1
  # MinGW
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
  - if "%type%"=="MinGW" set PATH=C:\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%type%"=="MinGW" set INCLUDE=C:\mingw64\x86_64-w64-mingw32\include;%INCLUDE%
  # CMake
  - '%command% "cmake --version"'
  # git
  - '%command% "git config --global user.name "AppVeyor""'
  - '%command% "git config --global user.email "team@appveyor.com""'
  - '%command% "git config --global push.default simple"'
  # gil
  - set PATH=C:\Python37;%PATH%
  - git clone https://github.com/chronoxor/gil.git"
  - cd sample
  - ..\gil\gil.bat update

# Build scripts
build_script:
  - cd CppLogging/build
  - '%build%'

# Test scripts
test: off
