name: Linux (clang)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup binutils-dev, uuid-dev
        run: sudo apt-get install -y binutils-dev uuid-dev

      - name: "Setup clang"
        uses: egor-tensin/setup-clang@v1

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          cd sample
          gil update

      - name: "Build"
        run: |
          cd sample/CppLogging/build
          ./unix.sh
